package com.alsorg.packing.reporting.service;

import jakarta.mail.internet.MimeMessage;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
public class EmailService {

    private final JavaMailSender mailSender;

    @Value("${app.mail.from}")
    private String from;

    @Value("${app.mail.reply-to:}")
    private String replyTo;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    public void sendExcel(
            String to,
            String subject,
            byte[] file,
            String filename
    ) {
        try {
            if (to == null || to.isBlank()) {
                throw new IllegalArgumentException("Recipient email is required");
            }

            if (file == null || file.length == 0) {
                throw new IllegalArgumentException("Excel attachment is empty");
            }

            MimeMessage message = mailSender.createMimeMessage();

            MimeMessageHelper helper = new MimeMessageHelper(
                    message,
                    true,
                    "UTF-8"
            );

            helper.setFrom(from);
            helper.setTo(to.trim());

            if (replyTo != null && !replyTo.isBlank()) {
                helper.setReplyTo(replyTo);
            }

            helper.setSubject(subject);

            helper.setText(
                    """
                    <div style="font-family:Arial,sans-serif;font-size:14px;color:#111827;">
                        <h2 style="margin:0 0 10px;">Alsorg Scheduled Report</h2>
                        <p>Please find the attached Excel report.</p>
                        <p style="color:#6b7280;font-size:12px;">
                            This is an automated report generated by Alsorg Inventory System.
                        </p>
                    </div>
                    """,
                    true
            );

            helper.addAttachment(
                    filename,
                    new ByteArrayResource(file),
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            );

            mailSender.send(message);

            System.out.println("✅ SMTP email sent successfully to: " + to);

        } catch (Exception e) {
            System.out.println("❌ SMTP email sending failed for: " + to);
            throw new RuntimeException("Email sending failed for: " + to, e);
        }
    }
}