package com.alsorg.packing.reporting.service;

import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
public class EmailService {

    private static final Logger log = LoggerFactory.getLogger(EmailService.class);

    private static final String XLSX_CONTENT_TYPE =
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

    private static final int MAX_SUBJECT_LENGTH = 240;
    private static final int MAX_FILENAME_LENGTH = 180;
    private static final int MAX_ATTACHMENT_BYTES = 50 * 1024 * 1024;

    private final JavaMailSender mailSender;

    @Value("${app.mail.from}")
    private String from;

    @Value("${app.mail.reply-to:}")
    private String replyTo;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    public void sendExcel(
            String to,
            String subject,
            byte[] file,
            String filename) {

        String cleanTo = requireMailbox(to, "Recipient email");
        String cleanFrom = requireMailbox(from, "Configured sender email");
        String cleanReplyTo = optionalMailbox(replyTo);
        String cleanSubject = cleanHeaderValue(subject, "Alsorg Scheduled Report", MAX_SUBJECT_LENGTH);
        String cleanFilename = cleanAttachmentFilename(filename);

        if (file == null || file.length == 0) {
            throw new IllegalArgumentException("Excel attachment is empty");
        }

        if (file.length > MAX_ATTACHMENT_BYTES) {
            throw new IllegalArgumentException("Excel attachment exceeds the maximum email size");
        }

        try {
            MimeMessage message = mailSender.createMimeMessage();

            MimeMessageHelper helper = new MimeMessageHelper(
                    message,
                    true,
                    "UTF-8");

            helper.setFrom(cleanFrom);
            helper.setTo(cleanTo);

            if (cleanReplyTo != null) {
                helper.setReplyTo(cleanReplyTo);
            }

            helper.setSubject(cleanSubject);

            helper.setText(
                    """
                    <div style="font-family:Arial,sans-serif;font-size:14px;color:#111827;">
                        <h2 style="margin:0 0 10px;">Alsorg Scheduled Report</h2>
                        <p>Please find the attached Excel report.</p>
                        <p style="color:#6b7280;font-size:12px;">
                            This is an automated report generated by Alsorg Inventory System.
                        </p>
                    </div>
                    """,
                    true);

            helper.addAttachment(
                    cleanFilename,
                    new ByteArrayResource(file),
                    XLSX_CONTENT_TYPE);

            mailSender.send(message);

            log.info(
                    "Scheduled report email sent successfully: recipient={}, bytes={}",
                    maskEmail(cleanTo),
                    file.length);

        } catch (Exception exception) {
            log.error(
                    "Scheduled report email failed: recipient={}",
                    maskEmail(cleanTo),
                    exception);

            throw new IllegalStateException("Email sending failed", exception);
        }
    }

    private String requireMailbox(
            String value,
            String fieldName) {
        String clean = value == null ? "" : value.trim();

        if (clean.isBlank()) {
            throw new IllegalArgumentException(fieldName + " is required");
        }

        try {
            InternetAddress address = new InternetAddress(clean, true);
            address.validate();

            if (!clean.equals(address.getAddress())) {
                throw new IllegalArgumentException(fieldName + " is invalid");
            }

            return clean;
        } catch (Exception exception) {
            throw new IllegalArgumentException(fieldName + " is invalid", exception);
        }
    }

    private String optionalMailbox(String value) {
        if (value == null || value.trim().isBlank()) {
            return null;
        }

        return requireMailbox(value, "Configured reply-to email");
    }

    private String cleanHeaderValue(
            String value,
            String fallback,
            int maxLength) {
        String clean = value == null ? "" : value
                .replace('\r', ' ')
                .replace('\n', ' ')
                .trim();

        if (clean.isBlank()) {
            clean = fallback;
        }

        if (clean.length() > maxLength) {
            clean = clean.substring(0, maxLength);
        }

        return clean;
    }

    private String cleanAttachmentFilename(String value) {
        String clean = cleanHeaderValue(
                value,
                "alsorg-report.xlsx",
                MAX_FILENAME_LENGTH)
                .replaceAll("[\\\\/:*?\"<>|]", "_");

        if (!clean.toLowerCase(java.util.Locale.ROOT).endsWith(".xlsx")) {
            clean = clean + ".xlsx";
        }

        return clean;
    }

    private String maskEmail(String value) {
        if (value == null || value.isBlank()) {
            return "-";
        }

        int at = value.indexOf('@');
        if (at <= 1) {
            return "***" + (at >= 0 ? value.substring(at) : "");
        }

        return value.substring(0, 1)
                + "***"
                + value.substring(at);
    }
}
