package com.alsorg.packing.controller;

import java.util.List;
import java.util.UUID;
import java.util.Map;
import com.alsorg.packing.service.PacketService;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import com.alsorg.packing.controller.dto.GeneratedPacketHistoryResponse;
import com.alsorg.packing.controller.dto.StickerHistoryResponse;
import com.alsorg.packing.domain.sticker.StickerHistory;
import com.alsorg.packing.domain.users.User;
import com.alsorg.packing.repository.StickerHistoryRepository;
import com.alsorg.packing.service.CurrentUserService;

@RestController
@RequestMapping("/api/stickers")
public class StickerHistoryController {

        private final StickerHistoryRepository repository;
        private final CurrentUserService currentUserService;
        private final PacketService packetService;

        public StickerHistoryController(
                        StickerHistoryRepository repository,
                        CurrentUserService currentUserService,
                        PacketService packetService) {
                this.repository = repository;
                this.currentUserService = currentUserService;
                this.packetService = packetService;
        }

        /*
         * GENERATED HISTORY
         *
         * ADMIN:
         * - Can see all generated history
         * - Can filter by generatedBy
         *
         * NON-ADMIN:
         * - Can only see own generated history
         */

        @GetMapping("/generated-history")
        public ResponseEntity<List<GeneratedPacketHistoryResponse>> generatedHistory(
                        @RequestParam(required = false) String generatedBy,
                        @RequestHeader(value = "Authorization", required = false) String auth) {
                User user = currentUserService.getCurrentUserFromAuth(auth);

                if (currentUserService.isAdmin(user)) {
                        if (generatedBy != null
                                        && !generatedBy.isBlank()
                                        && !"ALL".equalsIgnoreCase(generatedBy)) {
                                return ResponseEntity.ok(
                                                repository.findGeneratedPacketHistoryByUser(
                                                                generatedBy));
                        }

                        return ResponseEntity.ok(
                                        repository.findGeneratedPacketHistoryAll());
                }

                return ResponseEntity.ok(
                                repository.findGeneratedPacketHistoryByUser(
                                                user.getUsername()));
        }

        /*
         * GENERATED BY USER DROPDOWN
         *
         * ADMIN:
         * - Can see all users who generated stickers
         *
         * NON-ADMIN:
         * - Can only see own username
         */

        @GetMapping("/generated-history/users")
        public ResponseEntity<List<String>> generatedHistoryUsers(
                        @RequestHeader(value = "Authorization", required = false) String auth) {
                User user = currentUserService.getCurrentUserFromAuth(auth);

                if (currentUserService.isAdmin(user)) {
                        return ResponseEntity.ok(
                                        repository.findDistinctGeneratedByUsers());
                }

                return ResponseEntity.ok(
                                List.of(user.getUsername()));
        }

        /*
         * ITEM-WISE STICKER HISTORY
         */

        @GetMapping("/{itemId}/history")
        public List<StickerHistoryResponse> history(
                        @PathVariable UUID itemId) {
                return repository.findHistoryByItemId(itemId);
        }

        /*
         * GENERATED HISTORY PDF PREVIEW / DOWNLOAD
         *
         * ADMIN:
         * - Can open any generated sticker PDF
         *
         * NON-ADMIN:
         * - Can open only own generated sticker PDFs
         */

        @Transactional(readOnly = true)
        @GetMapping("/history/{historyId}/download-pdf")
        public ResponseEntity<byte[]> download(
                        @PathVariable UUID historyId,
                        @RequestHeader(value = "Authorization", required = false) String auth) {
                User user = currentUserService.getCurrentUserFromAuth(auth);

                StickerHistory history = repository.findById(historyId)
                                .orElseThrow(() -> new ResponseStatusException(
                                                HttpStatus.NOT_FOUND,
                                                "Sticker history not found"));

                if (!currentUserService.isAdmin(user)) {
                        String generatedBy = history.getGeneratedBy();

                        if (generatedBy == null
                                        || generatedBy.isBlank()
                                        || !generatedBy.equalsIgnoreCase(user.getUsername())) {
                                throw new ResponseStatusException(
                                                HttpStatus.FORBIDDEN,
                                                "You cannot access this sticker PDF");
                        }
                }

                byte[] pdfData = history.getPdfData();

                if (pdfData == null || pdfData.length == 0) {
                        throw new ResponseStatusException(
                                        HttpStatus.NOT_FOUND,
                                        "Sticker PDF not found");
                }

                String stickerNumber = history.getStickerNumber() != null
                                && !history.getStickerNumber().isBlank()
                                                ? history.getStickerNumber()
                                                : historyId.toString();

                return ResponseEntity.ok()
                                .header(
                                                HttpHeaders.CONTENT_DISPOSITION,
                                                "inline; filename="
                                                                + stickerNumber
                                                                + ".pdf")
                                .contentType(MediaType.APPLICATION_PDF)
                                .body(pdfData);
        }

        @PostMapping("/dispatched/{zohoItemId}/ensure-history")
        public ResponseEntity<Map<String, Object>> ensureHistoryForDispatchedItem(
                        @PathVariable String zohoItemId,
                        @RequestHeader(value = "Authorization", required = false) String auth) {
                User user = currentUserService.getCurrentUserFromAuth(auth);

                if (!currentUserService.isAdmin(user) &&
                                !currentUserService.isDispatch(user)) {
                        throw new ResponseStatusException(
                                        HttpStatus.FORBIDDEN,
                                        "Only ADMIN or DISPATCH can rebuild sticker history");
                }

                StickerHistory history = packetService.ensureStickerHistoryForDispatchedItem(
                                zohoItemId,
                                user.getUsername(),
                                currentUserService.allowedPlants(user));

                UUID packetItemId = history.getPacketItem() != null
                                ? history.getPacketItem().getId()
                                : null;

                if (packetItemId == null) {
                        throw new ResponseStatusException(
                                        HttpStatus.INTERNAL_SERVER_ERROR,
                                        "Packet item could not be resolved for sticker history");
                }

                return ResponseEntity.ok(
                                Map.of(
                                                "packetItemId", packetItemId.toString(),
                                                "historyId", history.getId().toString(),
                                                "stickerNumber", history.getStickerNumber(),
                                                "message", "Sticker history is ready"));
        }
}