import { useCallback, useEffect, useMemo, useState } from "react";
import { Box, Button, Card, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, TextField, Typography } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import ArrowBackOutlinedIcon from "@mui/icons-material/ArrowBackOutlined";
import RefreshOutlinedIcon from "@mui/icons-material/RefreshOutlined";
import { useNavigate, useParams } from "react-router-dom";
import { matflowApi, readMatFlowError } from "../api/matflowApi";
import { ErrorBox, LoadingBlock, PageHero, EmptyState, MatFlowStatusChip, pageSx, panelSx, fieldSx, primaryBtnSx, secondaryBtnSx, dialogPaperSx, dialogTitleSx, dialogContentSx, dialogActionsSx, useMatFlow, readable } from "../matflowUi";

export function MatFlowBomListPage(){
 const {selectedPlantParam}=useMatFlow(); const nav=useNavigate(); const [rows,setRows]=useState([]),[files,setFiles]=useState([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[fileId,setFileId]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [b,f]=await Promise.all([matflowApi.listBoms({search}),matflowApi.listProductionFiles({stage:"ENGINEERING_WORK",plantCode:selectedPlantParam})]);setRows(b.data||[]);setFiles(f.data||[]);}catch(e){setError(readMatFlowError(e));}finally{setLoading(false);}},[search,selectedPlantParam]);useEffect(()=>{load();},[load]);
 const create=async()=>{try{const r=await matflowApi.createBom({productionFileId:fileId,remarks:null});setOpen(false);nav(`/matflow/boms/${r.data.id}`);}catch(e){setError(readMatFlowError(e));}};
 if(loading&&!rows.length)return <LoadingBlock/>;
 return <Box sx={pageSx}><PageHero badge="ENGINEERING DOCUMENT" title="BOM Builder" subtitle="BOM is an Engineering release document in this phase. Material procurement, issue and production consumption are intentionally not implemented here." actions={<Box sx={{display:"flex",gap:1}}><Button startIcon={<RefreshOutlinedIcon/>} onClick={load} sx={secondaryBtnSx}>Refresh</Button><Button startIcon={<AddOutlinedIcon/>} onClick={()=>setOpen(true)} sx={primaryBtnSx}>New BOM</Button></Box>}/>{error&&<ErrorBox>{error}</ErrorBox>}
 <Card sx={{...panelSx,p:1.4}}><TextField fullWidth size="small" label="Search BOM, PD, product or drawing" value={search} onChange={e=>setSearch(e.target.value)} sx={fieldSx}/></Card>
 <Card sx={{...panelSx,p:0,overflow:"hidden"}}>{!rows.length?<EmptyState>No BOMs found.</EmptyState>:rows.map(r=><Box key={r.id} onClick={()=>nav(`/matflow/boms/${r.id}`)} sx={{px:1.5,py:1.2,borderBottom:"1px solid var(--mf-border)",display:"grid",gridTemplateColumns:{xs:"1fr",md:"1.25fr .9fr 1.2fr .7fr .7fr"},gap:1,alignItems:"center",cursor:"pointer","&:hover":{background:"var(--mf-hover)"}}}><Box><Typography sx={{fontSize:12,fontWeight:950,color:"var(--mf-text)"}}>{r.bomNumber}</Typography><Typography sx={{fontSize:10,color:"var(--mf-text-muted)"}}>{r.projectCode} · {r.productionFileNo}</Typography></Box><Typography sx={{fontSize:10.5,color:"var(--mf-text-secondary)"}}>{r.drawingNo}</Typography><Typography sx={{fontSize:11,fontWeight:850,color:"var(--mf-text)"}}>{r.productName}</Typography><Typography sx={{fontSize:10.5,color:"var(--mf-text-secondary)"}}>Rev {r.revisionNo}</Typography><MatFlowStatusChip status={r.status}/></Box>)}</Card>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm" PaperProps={{sx:dialogPaperSx}}><DialogTitle sx={dialogTitleSx}>Create Engineering BOM</DialogTitle><DialogContent sx={dialogContentSx}><Box sx={{pt:.8}}><TextField select fullWidth label="Production File" value={fileId} onChange={e=>setFileId(e.target.value)} sx={fieldSx}>{files.map(f=><MenuItem key={f.id} value={f.id}>{f.productionFileNo} · {f.projectCode} · {f.productName}</MenuItem>)}</TextField><Typography sx={{mt:1,fontSize:10.5,color:"var(--mf-text-muted)"}}>Only Engineering-approved files in Engineering Work are offered here.</Typography></Box></DialogContent><DialogActions sx={dialogActionsSx}><Button onClick={()=>setOpen(false)} sx={secondaryBtnSx}>Cancel</Button><Button disabled={!fileId} onClick={create} sx={primaryBtnSx}>Create</Button></DialogActions></Dialog>
 </Box>;
}

const lineBlank={materialId:"",materialCode:"",materialName:"",category:"",specification:"",uom:"NOS",requiredQty:"",wastagePercent:"0",remarks:""};
export function MatFlowBomDetailPage(){
 const {bomId}=useParams(); const nav=useNavigate(); const [bom,setBom]=useState(null),[materials,setMaterials]=useState([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[line,setLine]=useState(lineBlank);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [b,m]=await Promise.all([matflowApi.getBom(bomId),matflowApi.listMaterials({active:true})]);setBom(b.data);setMaterials(m.data||[]);}catch(e){setError(readMatFlowError(e));}finally{setLoading(false);}},[bomId]);useEffect(()=>{load();},[load]);
 const pickMaterial=(id)=>{const m=materials.find(x=>x.id===id);setLine(m?{...line,materialId:m.id,materialCode:m.materialCode,materialName:m.materialName,category:m.category,specification:m.specification||"",uom:m.uom}:line);};
 const add=async()=>{try{await matflowApi.addBomLine(bomId,{...line,requiredQty:Number(line.requiredQty),wastagePercent:Number(line.wastagePercent||0)});setOpen(false);setLine(lineBlank);await load();}catch(e){setError(readMatFlowError(e));}};
 const submit=async()=>{try{await matflowApi.submitBom(bomId,{remarks:bom.remarks,rowVersion:bom.rowVersion});await load();}catch(e){setError(readMatFlowError(e));}};
 const revision=async()=>{try{const r=await matflowApi.createBomRevision(bomId,{remarks:`Revision from ${bom.bomNumber}`,rowVersion:bom.rowVersion});nav(`/matflow/boms/${r.data.id}`);}catch(e){setError(readMatFlowError(e));}};
 const total=useMemo(()=>Number((bom?.lines||[]).reduce((a,x)=>a+Number(x.netRequiredQty||0),0).toFixed(3)),[bom]);
 if(loading)return <LoadingBlock/>; if(!bom)return <Box sx={pageSx}><ErrorBox>{error||"BOM not found."}</ErrorBox></Box>;
 return <Box sx={pageSx}><PageHero badge="ENGINEERING BOM" title={bom.bomNumber} subtitle={`${bom.projectCode} · ${bom.productionFileNo} · ${bom.productName} · ${bom.drawingNo}`} actions={<Box sx={{display:"flex",gap:1,flexWrap:"wrap"}}><Button startIcon={<ArrowBackOutlinedIcon/>} onClick={()=>nav("/matflow/boms")} sx={secondaryBtnSx}>Back</Button>{bom.status==="DRAFT"&&<Button startIcon={<AddOutlinedIcon/>} onClick={()=>setOpen(true)} sx={secondaryBtnSx}>Add Line</Button>}{bom.status==="DRAFT"&&<Button onClick={submit} sx={primaryBtnSx}>Ready for Release</Button>}{bom.status!=="DRAFT"&&bom.status!=="SUPERSEDED"&&<Button onClick={revision} sx={secondaryBtnSx}>Create Revision</Button>}</Box>}/>{error&&<ErrorBox>{error}</ErrorBox>}
 <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr 1fr",md:"repeat(5,1fr)"},gap:1}}>{[["Status",readable(bom.status)],["Revision",bom.revisionNo],["Lines",bom.lines?.length||0],["Net Qty Sum",total],["Latest",bom.latestRevision?"Yes":"No"]].map(([a,b])=><Card key={a} sx={{...panelSx,p:1.3}}><Typography sx={{fontSize:9.5,fontWeight:850,color:"var(--mf-text-muted)"}}>{a}</Typography><Typography sx={{mt:.3,fontSize:15,fontWeight:950,color:"var(--mf-text)"}}>{b}</Typography></Card>)}</Box>
 <Card sx={{...panelSx,p:0,overflow:"hidden"}}>{!(bom.lines||[]).length?<EmptyState>No BOM lines.</EmptyState>:(bom.lines||[]).map(x=><Box key={x.id} sx={{px:1.4,py:1.1,borderBottom:"1px solid var(--mf-border)",display:"grid",gridTemplateColumns:{xs:"1fr",md:".35fr .8fr 1.2fr .8fr .65fr .65fr .65fr"},gap:1,alignItems:"center"}}><Typography sx={{fontSize:10,color:"var(--mf-text-muted)"}}>{x.lineNo}</Typography><Typography sx={{fontSize:10.5,fontWeight:900,color:"var(--mf-text)"}}>{x.materialCode}</Typography><Typography sx={{fontSize:11,fontWeight:850,color:"var(--mf-text)"}}>{x.materialName}</Typography><Typography sx={{fontSize:10,color:"var(--mf-text-secondary)"}}>{x.category}</Typography><Typography sx={{fontSize:10.5,color:"var(--mf-text-secondary)"}}>{x.requiredQty} {x.uom}</Typography><Typography sx={{fontSize:10,color:"var(--mf-text-muted)"}}>{x.wastagePercent||0}% W</Typography><Typography sx={{fontSize:10.5,fontWeight:900,color:"var(--mf-text)"}}>{x.netRequiredQty}</Typography></Box>)}</Card>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm" PaperProps={{sx:dialogPaperSx}}><DialogTitle sx={dialogTitleSx}>Add BOM Line</DialogTitle><DialogContent sx={dialogContentSx}><Box sx={{pt:.6,display:"grid",gap:1.1}}><TextField select label="Material Master (optional)" value={line.materialId} onChange={e=>pickMaterial(e.target.value)} sx={fieldSx}><MenuItem value="">Manual line</MenuItem>{materials.map(m=><MenuItem key={m.id} value={m.id}>{m.materialCode} · {m.materialName}</MenuItem>)}</TextField><TextField label="Material Code" value={line.materialCode} onChange={e=>setLine({...line,materialCode:e.target.value})} sx={fieldSx}/><TextField label="Material Name" value={line.materialName} onChange={e=>setLine({...line,materialName:e.target.value})} sx={fieldSx}/><TextField label="Category" value={line.category} onChange={e=>setLine({...line,category:e.target.value})} sx={fieldSx}/><TextField label="Specification" value={line.specification} onChange={e=>setLine({...line,specification:e.target.value})} sx={fieldSx}/><TextField label="UOM" value={line.uom} onChange={e=>setLine({...line,uom:e.target.value})} sx={fieldSx}/><TextField type="number" label="Required Qty" value={line.requiredQty} onChange={e=>setLine({...line,requiredQty:e.target.value})} sx={fieldSx}/><TextField type="number" label="Wastage %" value={line.wastagePercent} onChange={e=>setLine({...line,wastagePercent:e.target.value})} sx={fieldSx}/></Box></DialogContent><DialogActions sx={dialogActionsSx}><Button onClick={()=>setOpen(false)} sx={secondaryBtnSx}>Cancel</Button><Button onClick={add} sx={primaryBtnSx}>Add</Button></DialogActions></Dialog>
 </Box>;
}
