import { useCallback, useEffect, useState } from "react";
import { Box, Button, Card, Typography } from "@mui/material";
import RefreshOutlinedIcon from "@mui/icons-material/RefreshOutlined";
import OpenInNewOutlinedIcon from "@mui/icons-material/OpenInNewOutlined";
import { useNavigate } from "react-router-dom";
import { matflowApi, readMatFlowError } from "../api/matflowApi";
import { ErrorBox, LoadingBlock, PageHero, EmptyState, MatFlowStatusChip, pageSx, panelSx, secondaryBtnSx, useMatFlow, readable } from "../matflowUi";
export function MatFlowReleasePage(){
 const {selectedPlantParam}=useMatFlow(); const nav=useNavigate(); const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [ready,released]=await Promise.all([matflowApi.listProductionFiles({stage:"PPC_GATE_2",plantCode:selectedPlantParam}),matflowApi.listProductionFiles({stage:"PRODUCTION_RELEASED",plantCode:selectedPlantParam})]);setRows([...(ready.data||[]),...(released.data||[])]);}catch(e){setError(readMatFlowError(e));}finally{setLoading(false);}},[selectedPlantParam]); useEffect(()=>{load();},[load]); if(loading)return <LoadingBlock/>;
 return <Box sx={pageSx}><PageHero badge="STABLE HANDOFF BOUNDARY" title="Production Release" subtitle="PPC Gate 2 releases a validated engineering package only. No Cutting, CNC, Drilling, Assembly or Final-QC workflow is created until that factory process is validated." actions={<Button startIcon={<RefreshOutlinedIcon/>} onClick={load} sx={secondaryBtnSx}>Refresh</Button>}/>{error&&<ErrorBox>{error}</ErrorBox>}
 <Card sx={{...panelSx,p:1.6,borderColor:"var(--mf-warning-border)",background:"var(--mf-warning-soft)"}}><Typography sx={{fontSize:12,fontWeight:950,color:"var(--mf-warning-text)"}}>Architecture guardrail</Typography><Typography sx={{mt:.35,fontSize:11,color:"var(--mf-text-secondary)"}}>PRODUCTION_RELEASED is an extension point, not a production-execution implementation. Later, the validated factory workflow will consume this released package. After Final QC, PackFlow will be linked by PD No./Project without duplicating Packing → Delivery.</Typography></Card>
 <Card sx={{...panelSx,p:0,overflow:"hidden"}}>{!rows.length?<EmptyState>No files at PPC Gate 2 or Production Released.</EmptyState>:rows.map(r=><Box key={r.id||r.productionFileId} sx={{px:1.5,py:1.2,borderBottom:"1px solid var(--mf-border)",display:"grid",gridTemplateColumns:{xs:"1fr",md:"1.1fr 1fr .9fr .7fr 1.4fr auto"},gap:1,alignItems:"center"}}><Box><Typography sx={{fontSize:12,fontWeight:950,color:"var(--mf-text)"}}>{r.productionFileNo}</Typography><Typography sx={{fontSize:10,color:"var(--mf-text-muted)"}}>{r.projectCode} · {r.productName}</Typography></Box><Typography sx={{fontSize:10.5,fontWeight:800,color:"var(--mf-text-secondary)"}}>{readable(r.stage)}</Typography><Typography sx={{fontSize:10.5,color:"var(--mf-text-secondary)"}}>{r.currentOwner||"—"}</Typography><MatFlowStatusChip status={r.releaseHealth}/><Typography sx={{fontSize:10,color:"var(--mf-text-muted)"}}>{r.stage==="PRODUCTION_RELEASED"?"Future workflow: not configured":"Awaiting PPC Gate 2"}</Typography><Button size="small" endIcon={<OpenInNewOutlinedIcon/>} onClick={()=>nav(`/matflow/work?fileId=${r.id||r.productionFileId}`)} sx={secondaryBtnSx}>Open</Button></Box>)}</Card>
 </Box>;
}
