package com.alsorg.packing.hrflow.domain;

public enum HrAuditAction {
    ACCESS_GRANTED,
    ACCESS_REVOKED,

    CANDIDATE_CREATED,
    APPLICATION_LINK_CREATED,
    APPLICATION_DRAFT_SAVED,
    APPLICATION_SUBMITTED,
    CANDIDATE_STAGE_CHANGED,
    CANDIDATE_UPDATED,
    CANDIDATE_DELETED,

    CANDIDATE_DOCUMENT_UPLOADED,
    CANDIDATE_DOCUMENT_ARCHIVED,

    ONBOARDING_CASE_CREATED,
    ONBOARDING_CASE_UPDATED,
    ONBOARDING_LINK_CREATED,

    POLICY_SNAPSHOT_UPDATED,
    POLICY_ACKNOWLEDGED,
    ORIENTATION_UPDATED,
    ORIENTATION_ACKNOWLEDGED,
    INDUCTION_FEEDBACK_SUBMITTED,
    NDA_SNAPSHOT_UPDATED,
    NDA_ACCEPTED,
    NDA_VERIFIED,
    DECLARATION_SNAPSHOT_UPDATED,
    DECLARATION_ACCEPTED,

    EMPLOYEE_CREATED,
    JOINING_CONFIRMED,
    JOINING_ACKNOWLEDGED,
    ONBOARDING_COMPLETED
}
