package com.alsorg.packing.hrflow.domain;

public enum HrDocumentType {
    PHOTO,
    RESUME,
    AADHAAR,
    PAN,
    DRIVING_LICENSE,
    EDUCATION_CERTIFICATE,
    EXPERIENCE_LETTER,
    ADDRESS_PROOF,
    OFFER_ACCEPTANCE,
    OTHER,

    // HRFLOW-managed encrypted workflow snapshots. These are not uploadable by candidates.
    ONBOARDING_POLICY_SNAPSHOT,
    ONBOARDING_POLICY_ACKNOWLEDGEMENT,
    ORIENTATION_STATE,
    ORIENTATION_RECORD,
    INDUCTION_FEEDBACK,
    NDA_SNAPSHOT,
    NDA_ACCEPTANCE,
    NDA_VERIFICATION,
    EMPLOYMENT_DECLARATION_SNAPSHOT,
    EMPLOYMENT_DECLARATION_ACCEPTANCE,
    JOINING_REPORT_SNAPSHOT,
    ONBOARDING_COMPLETION_RECORD
}
