package com.alsorg.packing.domain.venflow;

public enum VenFlowStage {

    /*
     * Active process stages.
     */
    INDENT_CREATED,
    SENT_TO_STORE,
    STORE_REVIEWED,

    STOCK_AVAILABLE,
    MATERIAL_RESERVED,

    PURCHASE_REQUEST_RAISED,
    PO_PENDING_DIRECTOR_APPROVAL,
    PO_APPROVED_BY_DIRECTOR,
    PO_REJECTED_BY_DIRECTOR,
    ORDER_PLACED_WITH_VENDOR,
    PO_RAISED,
    MATERIAL_RECEIVED_AT_STORE,
    GRN_DONE,

    QC_PENDING,
    QC_OK,
    QC_NOT_OK,

    MATERIAL_ACCEPTED_IN_STORE,
    MATERIAL_REJECTED_HOLD_RETURN,

    MATERIAL_ISSUED_TO_PRODUCTION,

    PROCESSING_STARTED,
    PROCESS_COMPLETED,
    SUPERVISOR_INFORMED,
    READY_FOR_NEXT_STAGE,

    /*
     * Legacy compatibility only.
     * Do not create new records using these values.
     */
    HEADER_CREATED,
    PRODUCT_DETAILS_FILLED,
    STORE_STATUS_UPDATED,
    REQUISITION_UPDATED,
    ORDER_QTY_UPDATED,
    EXPECTED_DATE_UPDATED,
    RECEIVED_QTY_UPDATED,
    COMPLETED,

    PRODUCTION_RAISED,
    STORE_REVIEWED_OLD,
    SENT_TO_PURCHASE,
    PO_APPROVED,
    MATERIAL_RECEIVED,
    MATERIAL_INFORMED,
    PRODUCTION_INFORMED,
    PRODUCTION_DETAILS_ADDED,
    PRODUCTION_STARTED,
    JOB_DONE
}