package com.alsorg.packing.domain.venflow;

public enum VenFlowStage {

    HEADER_CREATED,
    PRODUCT_DETAILS_FILLED,
    STORE_STATUS_UPDATED,
    REQUISITION_UPDATED,
    ORDER_QTY_UPDATED,
    EXPECTED_DATE_UPDATED,
    RECEIVED_QTY_UPDATED,
    COMPLETED,

    PRODUCTION_RAISED,
    STORE_REVIEWED,
    SENT_TO_PURCHASE,
    PO_RAISED,
    PO_APPROVED,
    MATERIAL_RECEIVED,
    MATERIAL_INFORMED,
    PRODUCTION_STARTED,
    JOB_DONE
}