package com.alsorg.packing.domain.venflow;

public enum VenFlowStage {

    INDENT_CREATED,
    SENT_TO_STORE,
    STORE_REVIEWED,

    STOCK_AVAILABLE,
    MATERIAL_RESERVED,

    PURCHASE_REQUEST_RAISED,
    PO_RAISED,
    MATERIAL_RECEIVED_AT_STORE,
    GRN_DONE,

    QC_PENDING,
    QC_OK,
    QC_NOT_OK,

    MATERIAL_ACCEPTED_IN_STORE,
    MATERIAL_REJECTED_HOLD_RETURN,

    PRODUCTION_INFORMED,
    PRODUCTION_DETAILS_ADDED,
    MATERIAL_ISSUED_TO_PRODUCTION,

    PROCESSING_STARTED,
    PROCESS_COMPLETED,
    SUPERVISOR_INFORMED,
    READY_FOR_NEXT_STAGE,

    /*
     * Legacy values kept temporarily for old rows.
     */
    HEADER_CREATED,
    PRODUCT_DETAILS_FILLED,
    STORE_STATUS_UPDATED,
    REQUISITION_UPDATED,
    ORDER_QTY_UPDATED,
    EXPECTED_DATE_UPDATED,
    RECEIVED_QTY_UPDATED,
    COMPLETED,

    PRODUCTION_RAISED,
    STORE_REVIEWED_OLD,
    SENT_TO_PURCHASE,
    PO_APPROVED,
    MATERIAL_RECEIVED,
    MATERIAL_INFORMED,
    PRODUCTION_STARTED,
    JOB_DONE
}