package com.alsorg.packing.domain.matflow;

public enum MatFlowLineStatus {
    NOT_REQUISITIONED,
    PARTIALLY_REQUISITIONED,
    REQUISITIONED,
    PARTIALLY_BLOCKED,
    FULLY_BLOCKED,
    SHORTAGE_IDENTIFIED,
    INDENT_RAISED,
    PROCUREMENT_IN_PROGRESS,
    PARTIALLY_RECEIVED,
    INSPECTION_PENDING,
    PARTIALLY_AVAILABLE_FOR_ISSUE,
    READY_FOR_ISSUE,
    PARTIALLY_ISSUED,
    FULLY_ISSUED,
    ON_HOLD,
    CANCELLED
}