package com.alsorg.packing.domain.matflow;

import java.time.LocalDateTime;

import com.alsorg.packing.domain.matflow.MatFlowPlanningTypes.IndentStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

@Entity
@Table(name = "mf_indents", uniqueConstraints = {
                @UniqueConstraint(name = "uk_mf_indent_number", columnNames = "indent_number")
}, indexes = {
                @Index(name = "idx_mf_indent_status", columnList = "status"),
                @Index(name = "idx_mf_indent_requisition", columnList = "requisition_id"),
                @Index(name = "idx_mf_indent_delivery", columnList = "deliver_to_location_id")
})
public class MatFlowIndent
                extends MatFlowBaseEntity {

        @Column(name = "indent_number", nullable = false, length = 120)
        public String indentNumber;

        @ManyToOne(fetch = FetchType.LAZY, optional = false)
        @JoinColumn(name = "requisition_id", nullable = false)
        public MatFlowMaterialRequisition requisition;

        @ManyToOne(fetch = FetchType.LAZY, optional = false)
        @JoinColumn(name = "project_drawing_id", nullable = false)
        public MatFlowProjectDrawing projectDrawing;

        @ManyToOne(fetch = FetchType.LAZY, optional = false)
        @JoinColumn(name = "bom_id", nullable = false)
        public MatFlowBom bom;

        /**
         * A purchase may be delivered directly to:
         * - Store
         * - QC
         * - Internal processing
         * - External processor
         */
        @ManyToOne(fetch = FetchType.LAZY, optional = false)
        @JoinColumn(name = "deliver_to_location_id", nullable = false)
        public MatFlowLocation deliverToLocation;

        @Enumerated(EnumType.STRING)
        @Column(name = "status", nullable = false, length = 50)
        public IndentStatus status = IndentStatus.AUTO_CREATED;

        @Column(name = "auto_generated", nullable = false)
        public boolean autoGenerated = true;

        @Column(name = "remarks", columnDefinition = "text")
        public String remarks;

        @Column(name = "submitted_to_purchase_by", length = 150)
        public String submittedToPurchaseBy;

        @Column(name = "submitted_to_purchase_at")
        public LocalDateTime submittedToPurchaseAt;
}