# =====================
# STAGING ENVIRONMENT
# =====================

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alsorg_staging
    username: alsorg_staging
    password: stag123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# =====================
# STICKER STORAGE
# =====================
sticker:
  storage:
    path: /data/alsorg/staging/stickers

# =====================
# SESSION
# =====================
server:
  address: 0.0.0.0
  port: 8080
  
  servlet:
    session:
      cookie:
        secure: false
        http-only: true


zoho:
  inventory:
    base-url: https://www.zohoapis.in
    organization-id: 60059178154
    client-id: 1000.3TWJVLYKTHPFLVZ3XHRM5C97MWD4BV
    client-secret: e05d933812b7350fb434374f706703315f8c2dc4b4
    refresh-token: 1000.ce1374d46a049381ba330719beec20ba.698acb13c7d5bf81b6105ead404d8000